- e: 'table||10'
  a: 'border="1" width="100%" cellspacing="0" cellpadding="10" style="margin: 20px auto"'
  c:
    - e: thead
      c:
        - e: 'tr||10'
          c:
            - e: 'td|Dayvu\Source\Classes\ElementProvider|10'
    - e: tbody
      c:
        - e: 'tr||10'
          c:
            - e: 'td|Tbody value|10'
    - e: tfoot
      c:
        - e: 'tr||10'
          c:
            - e: 'td|Tfoot value|10'